In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

## Creating Arrays

In [2]:
myList = [1, 2, 3]
arr = np.array(myList) #1 Dimensional Array/Vector
arr

array([1, 2, 3])

In [5]:
arr.shape

(3,)

In [9]:
myNewList = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(myNewList) #2 Dimensional Array/Matrix
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2.shape

(3, 3)

In [7]:
type(arr)

numpy.ndarray

In [10]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
np.arange(1, 10001)

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [14]:
np.arange(0, 101, 5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.zeros((5,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [21]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.full((10,20), 8)

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

## Random Arrays

In [37]:
np.random.rand(10,5) #Values between 0 and 1

array([[0.75641589, 0.56175329, 0.78047231, 0.72229212, 0.64265157],
       [0.95565588, 0.62346874, 0.70955218, 0.64820432, 0.83994223],
       [0.0079917 , 0.40369935, 0.56696335, 0.6771073 , 0.46260161],
       [0.66770879, 0.38022676, 0.61864312, 0.74154631, 0.88826603],
       [0.22443895, 0.043536  , 0.27120264, 0.86575151, 0.97931737],
       [0.58689797, 0.96876903, 0.87959835, 0.65721859, 0.59291472],
       [0.15529097, 0.10046304, 0.29385863, 0.31345523, 0.55364546],
       [0.98748896, 0.51084622, 0.63748378, 0.2349177 , 0.03111515],
       [0.05890542, 0.09162434, 0.18505513, 0.61104533, 0.48765239],
       [0.74234883, 0.94359876, 0.52647976, 0.8753669 , 0.7310508 ]])

In [55]:
np.random.randint(1,100,10)

array([47, 40, 72, 91, 38, 10, 96, 32, 58, 34])

In [51]:
randArr = np.random.randint(1, 100, (4,5))
randArr

array([[95, 12, 76, 33, 16],
       [74, 48,  5,  8, 38],
       [23,  2, 85, 73, 93],
       [99, 58, 55, 90, 74]])

In [32]:
randArr.min()

13

In [33]:
randArr.max()

99

In [34]:
randArr.argmin()

0

In [35]:
randArr.argmax()

8

## Reshaping Arrays

In [39]:
myArr = np.arange(1,26)
myArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [43]:
myMatrix = myArr.reshape(5,5)
myMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
myMatrix.reshape(25,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [45]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
newArr = np.arange(1,13)
newArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
newArr.shape

(12,)

In [48]:
newArr.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
newArr.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

## Indexing & Slicing

In [56]:
myArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [59]:
myArr[15]

16

In [57]:
myMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
myMatrix[2]

array([11, 12, 13, 14, 15])

In [61]:
myMatrix[2][3]

14

In [62]:
myArr[1:5]

array([2, 3, 4, 5])

In [63]:
myMatrix[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
myMatrix[:2, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [66]:
myArr[::-1]

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2,  1])

In [67]:
myArr[::-2]

array([25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [68]:
myArr[10:0:-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

## Sorting Arrays

In [69]:
unsortedArr = np.random.randint(1, 101, 10)
unsortedArr

array([48, 47,  8, 54, 13, 58, 88, 30,  7, 37])

In [70]:
unsortedArr.sort()

In [71]:
unsortedArr

array([ 7,  8, 13, 30, 37, 47, 48, 54, 58, 88])

In [72]:
unsortedArr = np.random.randint(1, 101, 10)
unsortedArr

array([24, 15, 63, 30, 28, 10, 44, 25, 65, 58])

In [74]:
sortedList = sorted(unsortedArr)
sortedList

[10, 15, 24, 25, 28, 30, 44, 58, 63, 65]

In [75]:
np.array(sortedList)

array([10, 15, 24, 25, 28, 30, 44, 58, 63, 65])

In [76]:
sorted(unsortedArr, reverse=True)

[65, 63, 58, 44, 30, 28, 25, 24, 15, 10]

In [77]:
np.array(sorted(unsortedArr, reverse=True))

array([65, 63, 58, 44, 30, 28, 25, 24, 15, 10])

In [78]:
sortedList.sort()

In [79]:
sortedList

[10, 15, 24, 25, 28, 30, 44, 58, 63, 65]

## Broadcasting

In [1]:
import numpy as np

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:5] = 100

In [5]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [6]:
arr[:] = 2000

In [7]:
arr

array([2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000])

## Slicing vs Copying

In [8]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
sliceOfArr = arr[:6]
sliceOfArr

array([1, 2, 3, 4, 5, 6])

In [10]:
sliceOfArr[:] = 99

In [11]:
sliceOfArr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [13]:
newArr = arr.copy()
newArr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [15]:
newArr[:] = 100
newArr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

## Fancy Indexing

In [17]:
myArr = np.arange(1,26).reshape(5,5)
myArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
myArr[2]

array([11, 12, 13, 14, 15])

In [19]:
myArr[[2, 4]]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [20]:
myArr[[2, 4, 1, 3, 0]]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5]])

In [22]:
myList = [1, 2, 3, 4]

print(myList[[0, 3, 2]])

TypeError: list indices must be integers or slices, not list

## Conditional Selection

In [23]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr > 5 #Boolean Array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [28]:
arr[(arr > 5) & (arr%2==0)]

array([ 6,  8, 10])

In [29]:
a = 20
b = 4

In [30]:
print(b and a)

20


In [31]:
print(b & a)

4


In [ ]:
& |

## Array Math

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

In [40]:
arr1 + arr2

array([11, 22, 33])

In [41]:
arr1 - arr2

array([ -9, -18, -27])

In [42]:
arr1 * arr2

array([10, 40, 90])

In [43]:
arr1 / arr2

array([0.1, 0.1, 0.1])

In [44]:
arr3 = np.array([10, 20, 30])
arr4 = np.array([5])

In [45]:
arr3 + arr4

array([15, 25, 35])

In [46]:
arr3 - arr4

array([ 5, 15, 25])

In [48]:
arr3 * arr4

array([ 50, 100, 150])

In [49]:
arr3 / arr4

array([2., 4., 6.])

In [50]:
np.add(arr1, arr2)

array([11, 22, 33])

## Scalar Functions

In [51]:
arr3

array([10, 20, 30])

In [52]:
arr3 / 10

array([1., 2., 3.])

In [53]:
arr3 + 10

array([20, 30, 40])

In [54]:
arr3 / 0

<ipython-input-54-cba86b3cfceb>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr3 / 0


array([inf, inf, inf])

## Universal Functions

In [55]:
np.sqrt(arr3)

array([3.16227766, 4.47213595, 5.47722558])

In [57]:
np.exp(arr3)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13])

In [58]:
np.sin(arr3)

array([-0.54402111,  0.91294525, -0.98803162])

In [59]:
np.cos(arr3)

array([-0.83907153,  0.40808206,  0.15425145])

In [60]:
np.tan(arr3)

array([ 0.64836083,  2.23716094, -6.4053312 ])

In [61]:
np.log(arr3)

array([2.30258509, 2.99573227, 3.40119738])

In [62]:
np.abs(arr3)

array([10, 20, 30])

In [63]:
np.max(arr3)

30

In [64]:
np.min(arr3)

10

In [ ]:
#Numpy Dot Product
np.dot()